title: Interest Rate Models
description: 
theme: just-the-docs

url: https://szhxnb.github.io/Interest-Rate-Models/

nav_enabled: true

defaults:
  - scope:
      path: "docs" 
      type: "pages"
    values:
      layout: "default"

back_to_top: true
back_to_top_text: "Back to top"

callouts:
  warning:
    title: Warning
    color: grey-dk
  hint:
    title: Hint
    color: grey-dk
  important:
    title: Important
    color: grey-dk
  note:
    title: Note
    color: grey-dk
  tip:
    title: Tip
    color: grey-dk
  caution:
    title: Caution
    color: grey-dk
  error:
    color: grey-dk
  attention:
    title: Attention
    color: grey-dk

color_scheme: dark
