title: Interest Rate Models
description: 
theme: just-the-docs

url: https://szhxnb.github.io/Interest-Rate-Models/

nav_enabled: true

defaults:
  - scope:
      path: "docs" 
      type: "pages"
    values:
      layout: "default"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'By Hengxu Zhu'

color_scheme: dark
